version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - pamiw-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pamiw-network

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    ports:
#      - "3000:3000"
#    environment:
#      PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK: true,
#      DATABASE_URL: "postgresql://postgres:password@db:5432/db?schema=public"
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#        - pamiw-network
networks:
  pamiw-network:
